
* [Throwable](#throwable)
  * [Error](#error)
  * [Exception](#exception)
* [try catch finally机制](#try-catch-finally机制)


## Throwable
### Error
表示 JVM 无法处理的错误
- OutOfMemoryError
- StackOverflowError
### Exception
- 受检异常
  - 需要用 try...catch... 语句捕获并进行处理，并且可以从异常中恢复；
    - IOException
      - ClassNotFoundException
- 非受检异常
  - 是程序运行时错误，例如除 0 会引发 Arithmetic Exception，此时程序崩溃并且无法恢复
    - RuntimeException
      - NullPointerException
      - IllegalArgumentException
## try catch finally机制
- 有当try代码块发生异常的时候，才会执行到catch代码块
- 不管try中是否发生异常，finally都会执行。
  - 以下两种情况例外：
    - 一：try中不发生异常时，try块中有System.exit(0);
    - 二：try中发生异常时，catch中有System.exit(0);
    - 说明：System.exit(0) 代码的作用的退出虚拟机;
- 若finally块内有return语句，则以finally块内的return为准
   - 如果try 或者 catch内也有return 其实是先执行了try 或者 catch代码块中的return语句的，
   - 但是由于finally的机制，执行完try或者catch内的代码以后并不会立刻结束函数，还会执行finally块代码，
   - 若finally也有return语句，则会覆盖try块或者catch块中的return语句
- 若finally代码块中有return语句，则屏蔽catch代码块中抛出的异常